#!/usr/bin/sh

# if ~/.config/nvim already exists, move it to ~/.config/nvim.bak
if [ -d ~/.config/nvim ]; then
    echo "Moving existing ~/.config/nvim to ~/.config/nvim.bak"
    mv ~/.config/nvim ~/.config/nvim.bak
fi

git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
cp init.lua ~/.config/nvim/init.lua

sudo cp ./tm /usr/local/bin/tm
cp .tmrc ~/.tmrc
